"""Typed contracts and tool-call validation.

``contracts.py`` is the single source of truth for tool names, argument shapes,
and validation constraints.  Use ``validate_tool_call()`` to check a parsed
``ToolCall`` against ``TOOL_SCHEMAS``.
"""

from .contracts import (
    ALLOWED_TOOLS,
    APPLY_PATCH_TOOL_NAME,
    BASH_TOOL_NAME,
    EDIT_TOOL_NAME,
    FILE_SEARCH_TOOL_NAME,
    LEGACY_EDIT_TOOL_ALIAS,
    LEGACY_TERMINAL_TOOL_ALIAS,
    READ_TOOL_NAME,
    TERMINAL_TOOL_NAME,
    TEXT_SEARCH_TOOL_NAME,
    TOOL_SCHEMAS,
    ActionEnvelope,
    AllowedTool,
    CanonicalFeedback,
    FeedbackPacket,
    SelfContainmentChecks,
    ToolCall,
    canonical_tool_name,
    make_tool_call,
    validate_tool_call,
)
from .rollout_records import RolloutRow, RolloutRowRequired
from .xml_action_schema import (
    XML_BUILTIN_ESCAPES,
    XML_CDATA_END,
    XML_THINK_ELEMENT,
    XML_TOOL_CALL_ELEMENT,
    XML_TOOL_NAME_ATTRIBUTE,
    XmlArgSchema,
    XmlToolSchema,
    get_xml_arg_order,
    get_xml_arg_schema,
    get_xml_list_item_tag,
    get_xml_tool_schema,
    iter_xml_tool_schemas,
    render_xml_arg_placeholder,
    render_xml_contract_signature,
    render_xml_tool_schema_line,
)

__all__ = [
    "ALLOWED_TOOLS",
    "APPLY_PATCH_TOOL_NAME",
    "BASH_TOOL_NAME",
    "EDIT_TOOL_NAME",
    "FILE_SEARCH_TOOL_NAME",
    "LEGACY_EDIT_TOOL_ALIAS",
    "LEGACY_TERMINAL_TOOL_ALIAS",
    "READ_TOOL_NAME",
    "TERMINAL_TOOL_NAME",
    "TEXT_SEARCH_TOOL_NAME",
    "TOOL_SCHEMAS",
    "ActionEnvelope",
    "AllowedTool",
    "CanonicalFeedback",
    "FeedbackPacket",
    "SelfContainmentChecks",
    "ToolCall",
    "canonical_tool_name",
    "RolloutRow",
    "RolloutRowRequired",
    "make_tool_call",
    "validate_tool_call",
    "XML_BUILTIN_ESCAPES",
    "XML_CDATA_END",
    "XML_THINK_ELEMENT",
    "XML_TOOL_CALL_ELEMENT",
    "XML_TOOL_NAME_ATTRIBUTE",
    "XmlArgSchema",
    "XmlToolSchema",
    "get_xml_arg_order",
    "get_xml_arg_schema",
    "get_xml_list_item_tag",
    "get_xml_tool_schema",
    "iter_xml_tool_schemas",
    "render_xml_arg_placeholder",
    "render_xml_contract_signature",
    "render_xml_tool_schema_line",
]
